# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
        only:
          - master
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: |
            LIVE_VERSION=`npm show react-native-modal-overlay version`
            PACKAGE_VERSION=`node -p "require('./package.json').version"`
            function ver { printf "%03d%03d%03d%03d" $(echo "$1" | tr '.' ' '); }
            if [ $(ver "$LIVE_VERSION") -lt $(ver "$PACKAGE_VERSION") ]; then npm publish; else echo "Not publishing since version hasn't increased"; fi
